# Generated by Django 4.2 on 2025-02-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantesProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('area', models.IntegerField(choices=[(1, 'Frontend'), (2, 'Backend'), (3, 'Fullstack'), (4, 'Mobile'), (5, 'DevOps'), (6, 'Gestão de Projetos'), (7, 'Analise de Dados'), (8, 'UI/UX'), (9, 'Testes'), (10, 'Outros')])),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosAndres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('stack', models.CharField(max_length=100)),
                ('versao', models.IntegerField()),
                ('producao', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
