# Generated by Django 4.2 on 2025-02-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appandres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participantesprojeto',
            table='participantes_projeto',
        ),
        migrations.AlterModelTable(
            name='projetosandres',
            table='projetos_andres',
        ),
    ]
