# Generated by Django 4.2 on 2025-02-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appandres', '0002_contratoparticipantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoparticipantes',
            name='duracao',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratoparticipantes',
            name='valor_contrato',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
