# Generated by Django 4.2 on 2025-02-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appandres', '0002_alter_participantesprojeto_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participantesprojeto',
            table='projeto_participante',
        ),
        migrations.AlterModelTable(
            name='projetosandres',
            table='projeto_andres',
        ),
    ]
