# Generated by Django 4.2 on 2025-02-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appandres', '0003_contratoparticipantes_duracao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratoparticipantes',
            old_name='duracao',
            new_name='data_fim',
        ),
        migrations.AddField(
            model_name='contratoparticipantes',
            name='data_inicio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
